# Site settings
title: ASP.NET Web API OData
email: odatafeedback@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains samples covering basic and advanced OData scenarios for
  ASP.NET Web API OData.
baseurl: "/WebApi" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  odata

permalink: /:categories/:title/

# Build settings
kramdown:
  input: GFM
